process.on('uncaughtException', function(err) {
    console.log('Threw Exception: ', err);
});
